version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: alquiclick-backend
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - alquiclick-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: alquiclick-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - alquiclick-network

  db:
    image: mysql:8.0
    container_name: alquiclick-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: alquiclick
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=root
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - alquiclick-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: alquiclick-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - alquiclick-network

networks:
  alquiclick-network:
    driver: bridge

volumes:
  dbdata:
    driver: local