version: '3'
services:
  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:latest
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: alquiClick
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
volumes:
  db_data:

networks:
  app_network:
    driver: "bridge"